### ISSUE TITLE
Press Page

### ISSUE THREAD

**Issue by Markj89** [firebelly/cfs#12]
New Page Built out. Went with similiar design as the other pages. However, this might be updated due to tabs on the Press  Release and News Section.  

![Screen Shot 2020-09-20 at 11 19 59 PM](https://user-images.githubusercontent.com/3435026/93732710-1f7b5a80-fb98-11ea-97c7-cc0f6bf15f3a.png)
![Screen Shot 2020-09-20 at 11 20 09 PM](https://user-images.githubusercontent.com/3435026/93732712-2013f100-fb98-11ea-8222-5a37b5589df9.png)

**Comment by poopsplat** [comment]
Closing because it's being addressed in #14
